import { PlatformNotification } from '@/types/platformAdmin';

export function getPlatformNotifications(): PlatformNotification[] {
  return [
    {
      id: 'notif-1',
      userId: 'super-admin',
      category: 'system',
      type: 'warning',
      title: 'High API Usage Detected',
      message: 'TechCorp Inc. has exceeded 80% of API rate limit',
      link: '/employers/emp-001',
      read: false,
      createdAt: '2024-01-14T10:30:00Z',
      relatedEntity: 'employer',
      entityId: 'emp-001',
      actionRequired: true,
    },
    {
      id: 'notif-2',
      userId: 'super-admin',
      category: 'approval',
      type: 'info',
      title: 'New Employer Registration',
      message: 'StartupX has completed registration and awaiting approval',
      link: '/employers/emp-250',
      read: false,
      createdAt: '2024-01-14T09:15:00Z',
      relatedEntity: 'employer',
      entityId: 'emp-250',
      actionRequired: true,
    },
    {
      id: 'notif-3',
      userId: 'super-admin',
      category: 'system',
      type: 'success',
      title: 'System Backup Completed',
      message: 'Daily backup completed successfully',
      read: false,
      createdAt: '2024-01-14T06:00:00Z',
      relatedEntity: 'system',
      actionRequired: false,
    },
    {
      id: 'notif-4',
      userId: 'super-admin',
      category: 'document',
      type: 'info',
      title: 'Contract Renewal Due',
      message: 'Enterprise Co. contract expires in 30 days',
      link: '/employers/emp-015',
      read: true,
      createdAt: '2024-01-13T14:20:00Z',
      relatedEntity: 'employer',
      entityId: 'emp-015',
      actionRequired: true,
    },
  ];
}
